const puppeteer = require('puppeteer');

const urls = [
    "https://ailzc.cn/pages/ab809d/",
    "https://ailzc.cn/pages/b81429/",
    "https://ailzc.cn/pages/9e7e97/",
    "https://ailzc.cn/pages/79a6c5/",
    "https://ailzc.cn/pages/ca8ff4/",
    "https://ailzc.cn/pages/96ade2/",
    "https://ailzc.cn/pages/35b866/",
    "https://ailzc.cn/pages/97f0cf/",
    "https://ailzc.cn/pages/f09e73/",
    "https://ailzc.cn/pages/cc4de8/",
    "https://ailzc.cn/pages/ae9551/",
    "https://ailzc.cn/pages/658baa/",
    "https://ailzc.cn/pages/cb5cab/",
    "https://ailzc.cn/pages/5b31ae/",
    "https://ailzc.cn/pages/154245/",
    "https://ailzc.cn/pages/4504a9/",
    "https://ailzc.cn/pages/b19e0c/",
    "https://ailzc.cn/pages/7a8e68/",
    "https://ailzc.cn/pages/f42ee1/",
    "https://ailzc.cn/pages/659ac5/",
    "https://ailzc.cn/pages/8700dd/",
    "https://ailzc.cn/pages/132488/",
    "https://ailzc.cn/pages/7040e1/",
    "https://ailzc.cn/pages/5edd24/",
    "https://ailzc.cn/pages/934895/",
    "https://ailzc.cn/pages/ebf74b/",
    "https://ailzc.cn/pages/542b11/",
    "https://ailzc.cn/pages/a5d720/",
    "https://ailzc.cn/pages/626f50/",
    "https://ailzc.cn/pages/232a61/",
    "https://ailzc.cn/pages/c1e9a5/",
    "https://ailzc.cn/pages/89116c/",
    "https://ailzc.cn/pages/5bd028/",
    "https://ailzc.cn/pages/cb9dfd/",
    "https://ailzc.cn/pages/8f820a/",
    "https://ailzc.cn/pages/8f820a/",
    "https://ailzc.cn/pages/c3dbe3/",
    "https://ailzc.cn/pages/e564cf/",
    "https://ailzc.cn/pages/e89e37/",
    "https://ailzc.cn/pages/9e2840/",
    "https://ailzc.cn/pages/f1b8d7/",
    "https://ailzc.cn/pages/c22d8b/",
    "https://ailzc.cn/pages/d0940a/",
    "https://ailzc.cn/pages/0f7872/",
    "https://ailzc.cn/pages/e50f8f/",
    "https://ailzc.cn/pages/5bf6e6/",
    "https://ailzc.cn/pages/b7e5d9/",
    "https://ailzc.cn/pages/01ddf8/",
    "https://ailzc.cn/pages/ac5873/",
    "https://ailzc.cn/pages/e793e5/",
    "https://ailzc.cn/pages/c11f79/",
    "https://ailzc.cn/pages/b3e427/",
    "https://ailzc.cn/pages/565be0/",
    "https://ailzc.cn/pages/f9e8a1/",
    "https://ailzc.cn/pages/18f121/",
    "https://ailzc.cn/pages/d75cf9/",
    "https://ailzc.cn/pages/e9a4e5/",
    "https://ailzc.cn/pages/75a193/",
    "https://ailzc.cn/pages/1d679e/",
    "https://ailzc.cn/pages/7159fb/",
    "https://ailzc.cn/pages/3262b1/",
    "https://ailzc.cn/pages/97f8fc/",
    "https://ailzc.cn/pages/6404d4/",
    "https://ailzc.cn/pages/0da331/",
    "https://ailzc.cn/pages/8e09f0/",
    "https://ailzc.cn/pages/8d0e4f/",
    "https://ailzc.cn/pages/8e79d3/",
    "https://ailzc.cn/pages/f4b8d7/",
    "https://ailzc.cn/pages/2f54dc/",
    "https://ailzc.cn/pages/a4eeb9/",
    "https://ailzc.cn/pages/759959/",
    "https://ailzc.cn/pages/d1b3d1/",
    "https://ailzc.cn/pages/182870/",
    "https://ailzc.cn/pages/1cbd27/",
    "https://ailzc.cn/pages/fa453c/",
    "https://ailzc.cn/pages/d92f21/",
    "https://ailzc.cn/pages/674ec5/",
    "https://ailzc.cn/pages/54b90a/",
    "https://ailzc.cn/pages/d92f21/",
    "https://ailzc.cn/pages/674ec5/",
    "https://ailzc.cn/pages/57f9da/",
    "https://ailzc.cn/pages/71b3ab/",
    "https://ailzc.cn/pages/0c337a/",
    "https://ailzc.cn/pages/0c337a/",
    "https://ailzc.cn/pages/69c646/",
    "https://ailzc.cn/pages/da9ecb/",
    "https://ailzc.cn/pages/2586e4/",
    "https://ailzc.cn/pages/fad713/",
    "https://ailzc.cn/pages/b150cb/",
    "https://ailzc.cn/pages/3561b5/",
    "https://ailzc.cn/pages/182870/",
    "https://ailzc.cn/pages/02d85d/",
    "https://ailzc.cn/pages/8c8c92/",
    "https://ailzc.cn/pages/2074c9/",
    "https://ailzc.cn/pages/38a368/",
    "https://ailzc.cn/pages/5575d9/",
    "https://ailzc.cn/pages/de4b0f/",
    "https://ailzc.cn/pages/0efdbb/",
    "https://ailzc.cn/pages/bbf355/",
    "https://ailzc.cn/pages/327f74/",
    "https://ailzc.cn/pages/e532ee/",
    "https://ailzc.cn/pages/435f86/",
    "https://ailzc.cn/pages/f0a55f/",
    "https://ailzc.cn/pages/ffc6e7/",
    "https://ailzc.cn/pages/c5876a/",
    "https://ailzc.cn/pages/60d603/",
    "https://ailzc.cn/pages/723475/",
    "https://ailzc.cn/pages/525aeb/",
    "https://ailzc.cn/pages/a80594/",
    "https://ailzc.cn/pages/3080ab/",
    "https://ailzc.cn/pages/9d4529/",
    "https://ailzc.cn/pages/76ac53/",
    "https://ailzc.cn/pages/45d349/",
    "https://ailzc.cn/pages/5a46ba/",
    "https://ailzc.cn/pages/2947b8/",
    "https://ailzc.cn/pages/d1182e/",
    "https://ailzc.cn/pages/fcf4d9/",
    "https://ailzc.cn/pages/18df9b/",
    "https://ailzc.cn/pages/1ec93d/",
    "https://ailzc.cn/pages/756ee5/",
    "https://ailzc.cn/pages/3d5cb3/",
    "https://ailzc.cn/pages/cd4728/",
    "https://ailzc.cn/pages/a49127/",
    "https://ailzc.cn/pages/d54306/",
    "https://ailzc.cn/pages/03d2f6/",
    "https://ailzc.cn/pages/0238a5/",
    "https://ailzc.cn/pages/eb88c2/",
    "https://ailzc.cn/pages/28b641/",
    "https://ailzc.cn/pages/8d3586/",
    "https://ailzc.cn/pages/4d5410/",
    "https://ailzc.cn/pages/bd3b05/",
    "https://ailzc.cn/pages/6a6c6a/",
    "https://ailzc.cn/pages/812583/",
    "https://ailzc.cn/pages/03507d/",
    "https://ailzc.cn/pages/0c359e/",
    "https://ailzc.cn/pages/9c3fa4/",
    "https://ailzc.cn/pages/7c3fa4/",
    "https://ailzc.cn/pages/200e93/",
    "https://ailzc.cn/pages/96583c/",
    "https://ailzc.cn/pages/e852aa/",
    "https://ailzc.cn/pages/095a30/",
    "https://ailzc.cn/pages/e2010a/",
    "https://ailzc.cn/pages/519030/",
    "https://ailzc.cn/pages/dfc19b/",
    "https://ailzc.cn/pages/6c1e78/",
    "https://ailzc.cn/pages/5e3f8a/",
    "https://ailzc.cn/pages/0b77ea/",
    "https://ailzc.cn/pages/c2119f/",
    "https://ailzc.cn/pages/c80e49/",
    "https://ailzc.cn/pages/8ce8ce/",
    "https://ailzc.cn/pages/4f8f8c/",
    "https://ailzc.cn/pages/ed2738/",
    "https://ailzc.cn/pages/bd3b05/",
    "https://ailzc.cn/pages/6a6c6a/",
    "https://ailzc.cn/pages/5e54b9/",
    "https://ailzc.cn/pages/cb91d7/",
    "https://ailzc.cn/pages/8cfec4/",
    "https://ailzc.cn/pages/8558a7/",
    "https://ailzc.cn/pages/bc728a/",
    "https://ailzc.cn/pages/ab809d/",
    "https://ailzc.cn/pages/b81429/",
    "https://ailzc.cn/pages/9e7e97/",
    "https://ailzc.cn/pages/79a6c5/",
    "https://ailzc.cn/pages/ca8ff4/",
    "https://ailzc.cn/pages/96ade2/",
    "https://ailzc.cn/pages/35b866/",
    "https://ailzc.cn/pages/97f0cf/",
    "https://ailzc.cn/pages/f09e73/",
    "https://ailzc.cn/pages/cc4de8/",
    "https://ailzc.cn/pages/ae9551/",
    "https://ailzc.cn/pages/658baa/",
    "https://ailzc.cn/pages/cb5cab/",
    "https://ailzc.cn/pages/5b31ae/",
    "https://ailzc.cn/pages/154245/",
    "https://ailzc.cn/pages/4504a9/",
    "https://ailzc.cn/pages/b19e0c/",
    "https://ailzc.cn/pages/7a8e68/",
    "https://ailzc.cn/pages/f42ee1/",
    "https://ailzc.cn/pages/659ac5/",
    "https://ailzc.cn/pages/8700dd/",
    "https://ailzc.cn/pages/132488/",
    "https://ailzc.cn/pages/7040e1/",
    "https://ailzc.cn/pages/5edd24/",
    "https://ailzc.cn/pages/934895/",
    "https://ailzc.cn/pages/ebf74b/",
    "https://ailzc.cn/pages/542b11/",
    "https://ailzc.cn/pages/a5d720/",
    "https://ailzc.cn/pages/626f50/",
    "https://ailzc.cn/pages/232a61/",
    "https://ailzc.cn/pages/c1e9a5/",
    "https://ailzc.cn/pages/89116c/",
    "https://ailzc.cn/pages/5bd028/",
    "https://ailzc.cn/pages/cb9dfd/",
    "https://ailzc.cn/pages/8f820a/",
    "https://ailzc.cn/pages/8f820a/",
    "https://ailzc.cn/pages/c3dbe3/",
    "https://ailzc.cn/pages/e564cf/",
    "https://ailzc.cn/pages/e89e37/",
    "https://ailzc.cn/pages/9e2840/",
    "https://ailzc.cn/pages/f1b8d7/",
    "https://ailzc.cn/pages/c22d8b/",
    "https://ailzc.cn/pages/d0940a/",
    "https://ailzc.cn/pages/0f7872/",
    "https://ailzc.cn/pages/e50f8f/",
    "https://ailzc.cn/pages/5bf6e6/",
    "https://ailzc.cn/pages/b7e5d9/",
    "https://ailzc.cn/pages/01ddf8/",
    "https://ailzc.cn/pages/ac5873/",
    "https://ailzc.cn/pages/e793e5/",
    "https://ailzc.cn/pages/c11f79/",
    "https://ailzc.cn/pages/b3e427/",
    "https://ailzc.cn/pages/565be0/",
    "https://ailzc.cn/pages/f9e8a1/",
    "https://ailzc.cn/pages/18f121/",
    "https://ailzc.cn/pages/d75cf9/",
    "https://ailzc.cn/pages/e9a4e5/",
    "https://ailzc.cn/pages/75a193/",
    "https://ailzc.cn/pages/1d679e/",
    "https://ailzc.cn/pages/7159fb/",
    "https://ailzc.cn/pages/3262b1/",
    "https://ailzc.cn/pages/97f8fc/",
    "https://ailzc.cn/pages/6404d4/",
    "https://ailzc.cn/pages/0da331/",
    "https://ailzc.cn/pages/8e09f0/",
    "https://ailzc.cn/pages/8d0e4f/",
    "https://ailzc.cn/pages/8e79d3/",
    "https://ailzc.cn/pages/f4b8d7/",
    "https://ailzc.cn/pages/2f54dc/",
    "https://ailzc.cn/pages/a4eeb9/",
    "https://ailzc.cn/pages/759959/",
    "https://ailzc.cn/pages/d1b3d1/",
    "https://ailzc.cn/pages/182870/",
    "https://ailzc.cn/pages/1cbd27/",
    "https://ailzc.cn/pages/fa453c/",
    "https://ailzc.cn/pages/d92f21/",
    "https://ailzc.cn/pages/674ec5/",
    "https://ailzc.cn/pages/54b90a/",
    "https://ailzc.cn/pages/d92f21/",
    "https://ailzc.cn/pages/674ec5/",
    "https://ailzc.cn/pages/57f9da/",
    "https://ailzc.cn/pages/71b3ab/",
    "https://ailzc.cn/pages/0c337a/",
    "https://ailzc.cn/pages/0c337a/",
    "https://ailzc.cn/pages/69c646/",
    "https://ailzc.cn/pages/da9ecb/",
    "https://ailzc.cn/pages/2586e4/",
    "https://ailzc.cn/pages/fad713/",
    "https://ailzc.cn/pages/b150cb/",
    "https://ailzc.cn/pages/3561b5/",
    "https://ailzc.cn/pages/182870/",
    "https://ailzc.cn/pages/02d85d/",
    "https://ailzc.cn/pages/8c8c92/",
    "https://ailzc.cn/pages/2074c9/",
    "https://ailzc.cn/pages/38a368/",
    "https://ailzc.cn/pages/5575d9/",
    "https://ailzc.cn/pages/de4b0f/",
    "https://ailzc.cn/pages/0efdbb/",
    "https://ailzc.cn/pages/bbf355/",
    "https://ailzc.cn/pages/327f74/",
    "https://ailzc.cn/pages/e532ee/",
    "https://ailzc.cn/pages/435f86/",
    "https://ailzc.cn/pages/f0a55f/",
    "https://ailzc.cn/pages/ffc6e7/",
    "https://ailzc.cn/pages/c5876a/",
    "https://ailzc.cn/pages/60d603/",
    "https://ailzc.cn/pages/723475/",
    "https://ailzc.cn/pages/525aeb/",
    "https://ailzc.cn/pages/a80594/",
    "https://ailzc.cn/pages/3080ab/",
    "https://ailzc.cn/pages/9d4529/",
    "https://ailzc.cn/pages/76ac53/",
    "https://ailzc.cn/pages/45d349/",
    "https://ailzc.cn/pages/5a46ba/",
    "https://ailzc.cn/pages/2947b8/",
    "https://ailzc.cn/pages/d1182e/",
    "https://ailzc.cn/pages/fcf4d9/",
    "https://ailzc.cn/pages/18df9b/",
    "https://ailzc.cn/pages/1ec93d/",
    "https://ailzc.cn/pages/756ee5/",
    "https://ailzc.cn/pages/3d5cb3/",
    "https://ailzc.cn/pages/cd4728/",
    "https://ailzc.cn/pages/a49127/",
    "https://ailzc.cn/pages/d54306/",
    "https://ailzc.cn/pages/03d2f6/",
    "https://ailzc.cn/pages/0238a5/",
    "https://ailzc.cn/pages/eb88c2/",
    "https://ailzc.cn/pages/28b641/",
    "https://ailzc.cn/pages/8d3586/",
    "https://ailzc.cn/pages/4d5410/",
    "https://ailzc.cn/pages/bd3b05/",
    "https://ailzc.cn/pages/6a6c6a/",
    "https://ailzc.cn/pages/812583/",
    "https://ailzc.cn/pages/03507d/",
    "https://ailzc.cn/pages/0c359e/",
    "https://ailzc.cn/pages/9c3fa4/",
    "https://ailzc.cn/pages/7c3fa4/",
    "https://ailzc.cn/pages/200e93/",
    "https://ailzc.cn/pages/96583c/",
    "https://ailzc.cn/pages/e852aa/",
    "https://ailzc.cn/pages/095a30/",
    "https://ailzc.cn/pages/e2010a/",
    "https://ailzc.cn/pages/519030/",
    "https://ailzc.cn/pages/dfc19b/",
    "https://ailzc.cn/pages/6c1e78/",
    "https://ailzc.cn/pages/5e3f8a/",
    "https://ailzc.cn/pages/0b77ea/",
    "https://ailzc.cn/pages/c2119f/",
    "https://ailzc.cn/pages/c80e49/",
    "https://ailzc.cn/pages/8ce8ce/",
    "https://ailzc.cn/pages/4f8f8c/",
    "https://ailzc.cn/pages/ed2738/",
    "https://ailzc.cn/pages/bd3b05/",
    "https://ailzc.cn/pages/6a6c6a/",
    "https://ailzc.cn/pages/5e54b9/",
    "https://ailzc.cn/pages/cb91d7/",
    "https://ailzc.cn/pages/8cfec4/",
    "https://ailzc.cn/pages/8558a7/",
    "https://ailzc.cn/pages/bc728a/"
];

const path = require('path');

(async () => {
    const userDataDir = path.join(__dirname, 'userData');
    const browser = await puppeteer.launch({
        userDataDir: userDataDir
    });

    for (let i = 0; i < urls.length; i++) {
        const page = await browser.newPage();
        // 降低deviceScaleFactor试试
        await page.setViewport({ width: 1200, height: 1920, deviceScaleFactor: 1 });

        // 设置更长的等待时间确保页面完全加载
        await page.goto(urls[i], { waitUntil: 'networkidle2', timeout: 60000 });

        // 等待页面稳定（可以根据需要调整等待时间）
        await new Promise(resolve => setTimeout(resolve, 2000));

        const pageTitle = await page.title();

        // 方法1：使用截图时确保页面不再有网络活动
        await page.screenshot({
            path: `images/${i}.${pageTitle}.png`,
            fullPage: true,
            captureBeyondViewport: false // 尝试关闭此选项
        });

        /* 方法2：如果上面方法不行，尝试手动模拟滚动并截取可视区域
        const bodyHandle = await page.$('body');
        const { height } = await bodyHandle.boundingBox();
        await bodyHandle.dispose();

        // 确定页面高度
        const viewportHeight = page.viewport().height;
        let screenshots = [];

        // 手动滚动并截取
        for (let scrollPos = 0; scrollPos < height; scrollPos += viewportHeight) {
            await page.evaluate(scrollPos => {
                window.scrollTo(0, scrollPos);
            }, scrollPos);

            await page.waitForTimeout(500); // 等待滚动稳定

            const screenshot = await page.screenshot();
            screenshots.push(screenshot);
        }

        // 这里需要用图像处理库如sharp来合并图片
        // 示例代码省略，需要额外安装sharp库
        */

        await page.close();
    }

    await browser.close();
})();